document.getElementById("header-container").style.backgroundColor = "#2fc18c";
document.getElementById("footer-container").style.backgroundColor = "#006dfb";
document.querySelector(".emergency-tasks").style.backgroundColor = "salmon";
document.querySelector(".no-emergency-tasks").style.backgroundColor = "yellow";
//document.getElementsByTagName("h3").style.backgroundColor = "purple";
document.querySelectorAll(".emergency-tasks h3")[0].style.backgroundColor = "purple";
document.querySelectorAll(".emergency-tasks h3")[1].style.backgroundColor = "purple";
document.querySelectorAll(".no-emergency-tasks h3")[0].style.backgroundColor = "black";
document.querySelectorAll(".no-emergency-tasks h3")[1].style.backgroundColor = "black";